---
abstract: 'Module to interface with the Solr (Lucene) webservice'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Mock::LWP: 0
  Test::More: 0
  XML::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Solr
no_index:
  directory:
    - inc
    - t
requires:
  Data::Page: 0
  Data::Pageset: 0
  Encode: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moose: 0
  URI: 1.28
  XML::Easy: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bricas/webservice-solr
version: 0.13
